name: Aurora Comments
description: "A Zeit Now ready Github based commenting system."
baseurl: /aurora-comments
url: https://mobihack.github.io
permalink: /blog/:title.html
sass:
  style: compressed
paginate: 5
paginate_path: "/blog/:num/"
markdown: kramdown

comments:
  enabled: true
  name: 'aurora-demo'
  url: 'https://aurora-comments.mobihack.now.sh/'
  levels: 3
  
plugins:
  - jekyll-paginate

exclude:
  - README.md
  - LICENSE
  - CNAME
  - vendor

sass:
  sass_dir: _sass